// SPDX-License-Identifier: MIT
// Canonical: docs/architecture.md §5.2 (Agent Permissions Gateway — ABI artifact pipeline)
pragma solidity ^0.8.24;

/// @title IVault
/// @notice The read surface `rmpc` uses on any deployed vault (issue #1464).
///         It is the compiler-owned source of `clients/rust-payment-client/abi/IVault.json`,
///         generated by `.github/scripts/generate_abi_bindings.sh` and drift-gated by suite-16.
///         It replaces the hand-maintained `MockVault.json`, which read real vaults through
///         a "TEST FIXTURE only" contract's ABI plus a hand-added `depositsPaused()`.
/// @dev    INTERFACE ONLY. No deployed vault inherits this file: vault bytecode and
///         inheritance are frozen, and inheriting an interface changes compiled metadata.
///         Every function below is a plain ERC-20 / ERC-4626 read, or the vault's public
///         `depositsPaused` flag. A selector rename in a real vault is caught by the
///         `rmpc` selector test and the fork e2e suite, not by the compiler.
interface IVault {
    /// @notice Vault share token name.
    function name() external view returns (string memory);

    /// @notice Vault share token symbol.
    function symbol() external view returns (string memory);

    /// @notice Vault share token decimals.
    function decimals() external view returns (uint8);

    /// @notice Total share supply.
    function totalSupply() external view returns (uint256);

    /// @notice Underlying asset address.
    function asset() external view returns (address);

    /// @notice Total underlying assets managed by the vault.
    function totalAssets() external view returns (uint256);

    /// @notice True when new deposits are paused. Withdrawals are never frozen.
    function depositsPaused() external view returns (bool);
}
