#!/bin/bash
set -e

echo "🚀 Starting Genesis Artifact Generation..."

# Define paths in the shared volume
SHARED_ROOT="/data"
GETH_DIR="$SHARED_ROOT/geth"
BEACON_CONFIG_DIR="$SHARED_ROOT/beacon-config"
VALIDATOR_KEYS_DIR="$SHARED_ROOT/validator_keys"
JWT_SECRET_PATH="$SHARED_ROOT/jwtsecret"

# Clean shared volume
rm -rf $SHARED_ROOT/*
# Clean ephemeral /data volume (if inherited from base image)
rm -rf /data/*

mkdir -p $GETH_DIR
mkdir -p $BEACON_CONFIG_DIR
mkdir -p $VALIDATOR_KEYS_DIR

echo "🧬 Generating Artifacts..."

# Explicitly set genesis timestamp to current time if not provided
if [ -z "$GENESIS_TIMESTAMP" ]; then
    export GENESIS_TIMESTAMP=$(date +%s)
    echo "⏰ Set GENESIS_TIMESTAMP to $GENESIS_TIMESTAMP"
fi

# EL Genesis
/work/entrypoint.sh el

# Issue #255: when the host has rendered a genesis alloc via
# `smoke-test-genesis-ingester` and bind-mounted it at /alloc-overlay.json
# (see docker-compose.alloc.yaml), merge it into the EL genesis.json's
# `alloc` map BEFORE the CL genesis is generated. The CL `genesis.ssz`
# embeds the EL genesis block hash (which depends on the alloc state
# root), so merging AFTER `entrypoint.sh cl` would leave the CL pointing
# at the pre-merge EL hash and `engine_forkchoiceUpdated` would forever
# disagree — chain RPC comes up but no block ever finalizes.
#
# Without the bind mount, the generated genesis keeps its default empty
# alloc — preserving the legacy clean-room behaviour for callers that
# haven't opted in yet.
if [ -f /alloc-overlay.json ]; then
    echo "🔁 Merging host-rendered alloc overlay (/alloc-overlay.json) into genesis.json"
    if ! command -v jq >/dev/null 2>&1; then
        echo "ERROR: jq required to merge alloc overlay but not present in image" >&2
        exit 1
    fi
    # The overlay JSON is a map { "0x…address": { balance, code, storage, … } }
    # whose entries follow geth's alloc schema. The merge expression
    # right-joins so overlay entries override (and add to) the existing
    # alloc — leaving any pre-seeded accounts intact.
    MERGED=/data/metadata/genesis.merged.json
    jq --slurpfile overlay /alloc-overlay.json \
       '.alloc = ((.alloc // {}) + $overlay[0])' \
       /data/metadata/genesis.json > "$MERGED"
    mv "$MERGED" /data/metadata/genesis.json
    echo "🔁 alloc overlay merged ($(jq '.alloc | length' /data/metadata/genesis.json) total entries)"
fi

# CL Genesis - Requires EL genesis.json to be in place (post-merge)!
/work/entrypoint.sh cl

# artifacts are generated by /work/entrypoint.sh using environment variables

echo "📂 Debugging Metadata contents:"
ls -la /data/metadata/

# Now move artifacts to final locations
# EL Genesis
mv /data/metadata/genesis.json $GETH_DIR/genesis.json

# CL Genesis - Copy ALL metadata (config.yaml, genesis.ssz, deploy_block.txt, etc.)
cp -r /data/metadata/* $BEACON_CONFIG_DIR/

# Rename deposit_contract_block.txt to deploy_block.txt if needed by Lighthouse
if [ -f "$BEACON_CONFIG_DIR/deposit_contract_block.txt" ]; then
    cp "$BEACON_CONFIG_DIR/deposit_contract_block.txt" "$BEACON_CONFIG_DIR/deploy_block.txt"
else 
    echo "0" > "$BEACON_CONFIG_DIR/deploy_block.txt"
fi

echo "📂 Content of Beacon Config Dir:"
ls -la $BEACON_CONFIG_DIR/

echo "🔑 Creating JWT Secret..."
openssl rand -hex 32 | tr -d "\n" > $JWT_SECRET_PATH

echo "🔐 Generating Validator Keys..."
rm -rf /keys/out
eth2-val-tools keystores \
  --insecure \
  --out-loc="/keys/out" \
  --source-mnemonic="giant issue aisle success illegal bike spike question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy very lucky have athlete" \
  --source-min=0 \
  --source-max=$NUMBER_OF_VALIDATORS

# Move raw keys to shared volume and organize by index for the validator nodes
echo "📂 Organizing keys by index..."
i=1
for key in /keys/out/teku-keys/*.json; do
    pubkey=$(basename "$key" .json)
    mkdir -p "$SHARED_ROOT/node-keys/$i"
    cp "$key" "$SHARED_ROOT/node-keys/$i/keystore.json"
    cp "/keys/out/teku-secrets/$pubkey.txt" "$SHARED_ROOT/node-keys/$i/password.txt"
    echo "  - Added key $pubkey to node-keys/$i"
    i=$((i + 1))
done

echo "✅ Artifact Generation Complete. Files are in $SHARED_ROOT"
echo "🎉 All Setup Complete."
