#!/usr/bin/env bash
# Cross-repo Fusion acceptance seam. Unlike the core dapp fixture test, this
# requires and consumes a receipt generated by robotmoney-frontend.
set -euo pipefail

fail() { echo "fusion-cross-repo: $*" >&2; exit 1; }

: "${FUSION_FRONTEND_RECEIPT_FILE:?point to a frontend-generated receipt artifact}"
: "${FUSION_FRONTEND_RECEIPT_URL:?set the stable public URL serving those exact bytes}"
: "${FUSION_RMPC_CONFIG:?set FUSION_RMPC_CONFIG}"
: "${FUSION_RECEIPT_ADDRESS:?set FUSION_RECEIPT_ADDRESS}"
: "${FUSION_RPC_URL:?set FUSION_RPC_URL}"
# INV-4 witnesses. Required, not optional: "release changed no allocation state"
# is an assertion this test makes, and an unset address would turn it into a
# silent skip (AC-CORE-04, AC-E2E-03, AC-E2E-04).
: "${FUSION_GOVERNANCE_ADDRESS:?set FUSION_GOVERNANCE_ADDRESS (RouterGovernance)}"
: "${FUSION_ROUTER_ADDRESS:?set FUSION_ROUTER_ADDRESS (PortfolioRouter)}"
# AC-CORE-04 names three witnesses — "vault balances, router weights, and
# proposal count" — and AC-E2E-03 repeats them. Weights and proposal count alone
# would miss an asset movement, so the mapped vaults are required too:
# comma-separated rmUSDC,rmPROTO,rmAGENT,rmRWA addresses from the 2.7 manifest.
: "${FUSION_VAULT_ADDRESSES:?set FUSION_VAULT_ADDRESSES (comma-separated mapped vault addresses)}"

RMPC_BIN="${RMPC_BIN:-rmpc}"
CAST_BIN="${CAST_BIN:-cast}"
command -v jq >/dev/null || fail "jq is required"

EVIDENCE_DIR="${FUSION_EVIDENCE_DIR:-}"
record() { # record <name> <content>
  [[ -n "$EVIDENCE_DIR" ]] || return 0
  mkdir -p "$EVIDENCE_DIR"
  printf '%s\n' "$2" >"$EVIDENCE_DIR/$1"
}

verify="$("$RMPC_BIN" receipt -c "$FUSION_RMPC_CONFIG" verify \
  --receipt-file "$FUSION_FRONTEND_RECEIPT_FILE")" || fail "frontend receipt failed core verification"
receipt_id="$(jq -er '.receipt_id' <<<"$verify")"
digest="$(jq -er '.payload_digest' <<<"$verify")"
record "core-verify-file.json" "$verify"

# AC-CORE-02 and AC-E2E-02 both require rmpc to fetch the STABLE PUBLIC URL and
# verify what is actually served there. `--receipt-file` reads local bytes while
# the URL is still what gets anchored as payloadUri (cli.rs: "The URL is still
# what gets anchored"), so verifying only the file would let a stale cache, a
# republish or a wrong session produce an on-chain (payloadDigest, payloadUri)
# pair the public URL does not reproduce — with this script still reporting the
# core_verify stage as passed. Fetch it, and prove the two agree.
verify_url="$("$RMPC_BIN" receipt -c "$FUSION_RMPC_CONFIG" verify \
  --receipt-url "$FUSION_FRONTEND_RECEIPT_URL")" \
  || fail "the bytes served at $FUSION_FRONTEND_RECEIPT_URL failed core verification"
record "core-verify-url.json" "$verify_url"
url_receipt_id="$(jq -er '.receipt_id' <<<"$verify_url")"
url_digest="$(jq -er '.payload_digest' <<<"$verify_url")"
[[ "$url_digest" == "$digest" ]] \
  || fail "the URL being anchored serves different bytes than the file being submitted \
(url payload_digest $url_digest, file payload_digest $digest)"
[[ "$url_receipt_id" == "$receipt_id" ]] \
  || fail "the URL being anchored derives receipt_id $url_receipt_id, file derives $receipt_id"

# INV-4 "before" witnesses, read before anything is submitted.
proposals_before="$("$CAST_BIN" call "$FUSION_GOVERNANCE_ADDRESS" \
  'currentProposalId()(uint256)' --rpc-url "$FUSION_RPC_URL")" \
  || fail "could not read RouterGovernance.currentProposalId()"
weights_before="$("$CAST_BIN" call "$FUSION_ROUTER_ADDRESS" \
  'getWeights()(address[],uint256[])' --rpc-url "$FUSION_RPC_URL")" \
  || fail "could not read PortfolioRouter.getWeights()"

IFS=',' read -r -a VAULTS <<<"$FUSION_VAULT_ADDRESSES"
(( ${#VAULTS[@]} > 0 )) || fail "FUSION_VAULT_ADDRESSES is empty"
read_balances() {
  local v out=""
  for v in "${VAULTS[@]}"; do
    v="${v// /}"
    local ta
    ta="$("$CAST_BIN" call "$v" 'totalAssets()(uint256)' --rpc-url "$FUSION_RPC_URL")" \
      || fail "could not read totalAssets() for vault $v"
    out+="$v=$(tr -d '[:space:]' <<<"$ta")"$'\n'
  done
  printf '%s' "$out"
}
balances_before="$(read_balances)"

FUSION_RECEIPT_FILE="$FUSION_FRONTEND_RECEIPT_FILE" \
FUSION_RECEIPT_URL="$FUSION_FRONTEND_RECEIPT_URL" \
FUSION_MAX_ATTEMPTS="${FUSION_MAX_ATTEMPTS:-5}" \
"$(dirname "$0")/submit-receipt-worker.sh"

# D9 permits a local/devnet release ceremony. Use a keystore, never a private
# key on argv. Timelock-controlled staging must perform its normal schedule /
# delay / execute ceremony externally, then rerun with FUSION_SKIP_RELEASE=1.
if [[ "${FUSION_SKIP_RELEASE:-0}" != "1" ]]; then
  : "${FUSION_RELEASE_KEYSTORE:?required for direct local/devnet release}"
  : "${FUSION_RELEASE_PASSWORD_FILE:?required for direct local/devnet release}"
  "$CAST_BIN" send "$FUSION_RECEIPT_ADDRESS" 'releaseReceipt(bytes32)' "$receipt_id" \
    --rpc-url "$FUSION_RPC_URL" --keystore "$FUSION_RELEASE_KEYSTORE" \
    --password-file "$FUSION_RELEASE_PASSWORD_FILE" >/dev/null
fi

released="$("$CAST_BIN" call "$FUSION_RECEIPT_ADDRESS" 'isReleased(bytes32)(bool)' \
  "$receipt_id" --rpc-url "$FUSION_RPC_URL")"
[[ "$released" == "true" ]] || fail "receipt is anchored but not released"

draft="$("$RMPC_BIN" governance -c "$FUSION_RMPC_CONFIG" draft-proposal \
  --receipt-id "$receipt_id" --receipt-file "$FUSION_FRONTEND_RECEIPT_FILE")" \
  || fail "released frontend receipt did not produce a governance handoff result"
jq -e --arg id "$receipt_id" \
  '.ok == true and (.drafts | length == 1) and .drafts[0].receipt_id == $id and
   (.drafts[0].status == "ready_for_review" or .drafts[0].status == "blocked_active_proposal" or .drafts[0].status == "skipped_no_weights")' \
  <<<"$draft" >/dev/null || fail "unexpected governance draft output"

# INV-4 "after" witnesses. Record and release are signalling-only: a drafted
# proposal is a JSON document for a human, so nothing here may have moved.
proposals_after="$("$CAST_BIN" call "$FUSION_GOVERNANCE_ADDRESS" \
  'currentProposalId()(uint256)' --rpc-url "$FUSION_RPC_URL")" \
  || fail "could not re-read RouterGovernance.currentProposalId()"
weights_after="$("$CAST_BIN" call "$FUSION_ROUTER_ADDRESS" \
  'getWeights()(address[],uint256[])' --rpc-url "$FUSION_RPC_URL")" \
  || fail "could not re-read PortfolioRouter.getWeights()"
balances_after="$(read_balances)"

[[ "$balances_after" == "$balances_before" ]] \
  || fail "INV-4 violated: mapped vault totalAssets changed across record/release
before:
$balances_before
after:
$balances_after"

[[ "$proposals_after" == "$proposals_before" ]] \
  || fail "INV-4 violated: RouterGovernance.currentProposalId moved \
$proposals_before -> $proposals_after; release submitted a proposal"
[[ "$weights_after" == "$weights_before" ]] \
  || fail "INV-4 violated: PortfolioRouter weights changed across record/release"

balances_json() { # name=value lines -> {"0x..":"123"}
  jq -Rn '[inputs | select(length>0) | split("=") | {key:.[0],value:.[1]}] | from_entries'
}

jq -n --arg receipt_id "$receipt_id" --arg payload_digest "$digest" \
  --arg receipt_url "$FUSION_FRONTEND_RECEIPT_URL" --arg url_digest "$url_digest" \
  --arg proposal_id_before "$proposals_before" --arg proposal_id_after "$proposals_after" \
  --argjson balances_before "$(balances_json <<<"$balances_before")" \
  --argjson balances_after "$(balances_json <<<"$balances_after")" \
  '{ok:true,
    stages:["frontend_artifact","core_verify_file","core_verify_url","submit","release","proposal_drafted","inv4_unchanged"],
    receipt_id:$receipt_id,payload_digest:$payload_digest,
    anchored_url:{url:$receipt_url,payload_digest:$url_digest,matches_submitted_bytes:true},
    inv4:{proposal_id_before:$proposal_id_before,proposal_id_after:$proposal_id_after,
          router_weights_unchanged:true,
          vault_total_assets_before:$balances_before,
          vault_total_assets_after:$balances_after,
          vault_balances_unchanged:true}}'
